In [2]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(Qobj())

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]


In [4]:
x = np.array([[1, 2, 3, 4, 5]])
print(Qobj(x))


Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]


In [5]:
r = np.random.rand(4, 4)
print(Qobj(r))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.20588488 0.51033756 0.93632751 0.10698709]
 [0.91270257 0.7225124  0.73638967 0.99248906]
 [0.82861931 0.42123753 0.81606952 0.0546676 ]
 [0.98028693 0.28368934 0.59175989 0.750243  ]]
